# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/intelligent-auto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/intelligent-auto/openauto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/intelligent-auto/openauto/CMakeFiles /home/pi/intelligent-auto/openauto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/intelligent-auto/openauto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ia

# Build rule for target.
ia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ia
.PHONY : ia

# fast build rule for target.
ia/fast:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/build
.PHONY : ia/fast

#=============================================================================
# Target rules for targets named ia_automoc

# Build rule for target.
ia_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ia_automoc
.PHONY : ia_automoc

# fast build rule for target.
ia_automoc/fast:
	$(MAKE) -f CMakeFiles/ia_automoc.dir/build.make CMakeFiles/ia_automoc.dir/build
.PHONY : ia_automoc/fast

#=============================================================================
# Target rules for targets named aasdk

# Build rule for target.
aasdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aasdk
.PHONY : aasdk

# fast build rule for target.
aasdk/fast:
	$(MAKE) -f aasdk/CMakeFiles/aasdk.dir/build.make aasdk/CMakeFiles/aasdk.dir/build
.PHONY : aasdk/fast

#=============================================================================
# Target rules for targets named aasdk_proto

# Build rule for target.
aasdk_proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aasdk_proto
.PHONY : aasdk_proto

# fast build rule for target.
aasdk_proto/fast:
	$(MAKE) -f aasdk/aasdk_proto/CMakeFiles/aasdk_proto.dir/build.make aasdk/aasdk_proto/CMakeFiles/aasdk_proto.dir/build
.PHONY : aasdk_proto/fast

#=============================================================================
# Target rules for targets named autoapp

# Build rule for target.
autoapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoapp
.PHONY : autoapp

# fast build rule for target.
autoapp/fast:
	$(MAKE) -f openauto/CMakeFiles/autoapp.dir/build.make openauto/CMakeFiles/autoapp.dir/build
.PHONY : autoapp/fast

#=============================================================================
# Target rules for targets named btservice

# Build rule for target.
btservice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btservice
.PHONY : btservice

# fast build rule for target.
btservice/fast:
	$(MAKE) -f openauto/CMakeFiles/btservice.dir/build.make openauto/CMakeFiles/btservice.dir/build
.PHONY : btservice/fast

#=============================================================================
# Target rules for targets named auto

# Build rule for target.
auto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auto
.PHONY : auto

# fast build rule for target.
auto/fast:
	$(MAKE) -f openauto/CMakeFiles/auto.dir/build.make openauto/CMakeFiles/auto.dir/build
.PHONY : auto/fast

#=============================================================================
# Target rules for targets named autoapp_automoc

# Build rule for target.
autoapp_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoapp_automoc
.PHONY : autoapp_automoc

# fast build rule for target.
autoapp_automoc/fast:
	$(MAKE) -f openauto/CMakeFiles/autoapp_automoc.dir/build.make openauto/CMakeFiles/autoapp_automoc.dir/build
.PHONY : autoapp_automoc/fast

#=============================================================================
# Target rules for targets named btservice_automoc

# Build rule for target.
btservice_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btservice_automoc
.PHONY : btservice_automoc

# fast build rule for target.
btservice_automoc/fast:
	$(MAKE) -f openauto/CMakeFiles/btservice_automoc.dir/build.make openauto/CMakeFiles/btservice_automoc.dir/build
.PHONY : btservice_automoc/fast

#=============================================================================
# Target rules for targets named auto_automoc

# Build rule for target.
auto_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auto_automoc
.PHONY : auto_automoc

# fast build rule for target.
auto_automoc/fast:
	$(MAKE) -f openauto/CMakeFiles/auto_automoc.dir/build.make openauto/CMakeFiles/auto_automoc.dir/build
.PHONY : auto_automoc/fast

ia_automoc.o: ia_automoc.cpp.o

.PHONY : ia_automoc.o

# target to build an object file
ia_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.cpp.o
.PHONY : ia_automoc.cpp.o

ia_automoc.i: ia_automoc.cpp.i

.PHONY : ia_automoc.i

# target to preprocess a source file
ia_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.cpp.i
.PHONY : ia_automoc.cpp.i

ia_automoc.s: ia_automoc.cpp.s

.PHONY : ia_automoc.s

# target to generate assembly for a file
ia_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.cpp.s
.PHONY : ia_automoc.cpp.s

ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.o: ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.o

.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.o

# target to build an object file
ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.o
.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.o

ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.i: ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.i

.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.i

# target to preprocess a source file
ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.i
.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.i

ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.s: ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.s

.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.s

# target to generate assembly for a file
ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.s
.PHONY : ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.cpp.s

src/app/bluetooth.o: src/app/bluetooth.cpp.o

.PHONY : src/app/bluetooth.o

# target to build an object file
src/app/bluetooth.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.o
.PHONY : src/app/bluetooth.cpp.o

src/app/bluetooth.i: src/app/bluetooth.cpp.i

.PHONY : src/app/bluetooth.i

# target to preprocess a source file
src/app/bluetooth.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.i
.PHONY : src/app/bluetooth.cpp.i

src/app/bluetooth.s: src/app/bluetooth.cpp.s

.PHONY : src/app/bluetooth.s

# target to generate assembly for a file
src/app/bluetooth.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/bluetooth.cpp.s
.PHONY : src/app/bluetooth.cpp.s

src/app/config.o: src/app/config.cpp.o

.PHONY : src/app/config.o

# target to build an object file
src/app/config.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.o
.PHONY : src/app/config.cpp.o

src/app/config.i: src/app/config.cpp.i

.PHONY : src/app/config.i

# target to preprocess a source file
src/app/config.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.i
.PHONY : src/app/config.cpp.i

src/app/config.s: src/app/config.cpp.s

.PHONY : src/app/config.s

# target to generate assembly for a file
src/app/config.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/config.cpp.s
.PHONY : src/app/config.cpp.s

src/app/tabs/data.o: src/app/tabs/data.cpp.o

.PHONY : src/app/tabs/data.o

# target to build an object file
src/app/tabs/data.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.o
.PHONY : src/app/tabs/data.cpp.o

src/app/tabs/data.i: src/app/tabs/data.cpp.i

.PHONY : src/app/tabs/data.i

# target to preprocess a source file
src/app/tabs/data.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.i
.PHONY : src/app/tabs/data.cpp.i

src/app/tabs/data.s: src/app/tabs/data.cpp.s

.PHONY : src/app/tabs/data.s

# target to generate assembly for a file
src/app/tabs/data.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/data.cpp.s
.PHONY : src/app/tabs/data.cpp.s

src/app/tabs/media.o: src/app/tabs/media.cpp.o

.PHONY : src/app/tabs/media.o

# target to build an object file
src/app/tabs/media.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.o
.PHONY : src/app/tabs/media.cpp.o

src/app/tabs/media.i: src/app/tabs/media.cpp.i

.PHONY : src/app/tabs/media.i

# target to preprocess a source file
src/app/tabs/media.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.i
.PHONY : src/app/tabs/media.cpp.i

src/app/tabs/media.s: src/app/tabs/media.cpp.s

.PHONY : src/app/tabs/media.s

# target to generate assembly for a file
src/app/tabs/media.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/media.cpp.s
.PHONY : src/app/tabs/media.cpp.s

src/app/tabs/open_auto.o: src/app/tabs/open_auto.cpp.o

.PHONY : src/app/tabs/open_auto.o

# target to build an object file
src/app/tabs/open_auto.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/open_auto.cpp.o
.PHONY : src/app/tabs/open_auto.cpp.o

src/app/tabs/open_auto.i: src/app/tabs/open_auto.cpp.i

.PHONY : src/app/tabs/open_auto.i

# target to preprocess a source file
src/app/tabs/open_auto.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/open_auto.cpp.i
.PHONY : src/app/tabs/open_auto.cpp.i

src/app/tabs/open_auto.s: src/app/tabs/open_auto.cpp.s

.PHONY : src/app/tabs/open_auto.s

# target to generate assembly for a file
src/app/tabs/open_auto.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/open_auto.cpp.s
.PHONY : src/app/tabs/open_auto.cpp.s

src/app/tabs/settings.o: src/app/tabs/settings.cpp.o

.PHONY : src/app/tabs/settings.o

# target to build an object file
src/app/tabs/settings.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.o
.PHONY : src/app/tabs/settings.cpp.o

src/app/tabs/settings.i: src/app/tabs/settings.cpp.i

.PHONY : src/app/tabs/settings.i

# target to preprocess a source file
src/app/tabs/settings.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.i
.PHONY : src/app/tabs/settings.cpp.i

src/app/tabs/settings.s: src/app/tabs/settings.cpp.s

.PHONY : src/app/tabs/settings.s

# target to generate assembly for a file
src/app/tabs/settings.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/tabs/settings.cpp.s
.PHONY : src/app/tabs/settings.cpp.s

src/app/theme.o: src/app/theme.cpp.o

.PHONY : src/app/theme.o

# target to build an object file
src/app/theme.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.o
.PHONY : src/app/theme.cpp.o

src/app/theme.i: src/app/theme.cpp.i

.PHONY : src/app/theme.i

# target to preprocess a source file
src/app/theme.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.i
.PHONY : src/app/theme.cpp.i

src/app/theme.s: src/app/theme.cpp.s

.PHONY : src/app/theme.s

# target to generate assembly for a file
src/app/theme.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/theme.cpp.s
.PHONY : src/app/theme.cpp.s

src/app/widgets/progress.o: src/app/widgets/progress.cpp.o

.PHONY : src/app/widgets/progress.o

# target to build an object file
src/app/widgets/progress.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.o
.PHONY : src/app/widgets/progress.cpp.o

src/app/widgets/progress.i: src/app/widgets/progress.cpp.i

.PHONY : src/app/widgets/progress.i

# target to preprocess a source file
src/app/widgets/progress.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.i
.PHONY : src/app/widgets/progress.cpp.i

src/app/widgets/progress.s: src/app/widgets/progress.cpp.s

.PHONY : src/app/widgets/progress.s

# target to generate assembly for a file
src/app/widgets/progress.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/progress.cpp.s
.PHONY : src/app/widgets/progress.cpp.s

src/app/widgets/switch.o: src/app/widgets/switch.cpp.o

.PHONY : src/app/widgets/switch.o

# target to build an object file
src/app/widgets/switch.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.o
.PHONY : src/app/widgets/switch.cpp.o

src/app/widgets/switch.i: src/app/widgets/switch.cpp.i

.PHONY : src/app/widgets/switch.i

# target to preprocess a source file
src/app/widgets/switch.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.i
.PHONY : src/app/widgets/switch.cpp.i

src/app/widgets/switch.s: src/app/widgets/switch.cpp.s

.PHONY : src/app/widgets/switch.s

# target to generate assembly for a file
src/app/widgets/switch.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/switch.cpp.s
.PHONY : src/app/widgets/switch.cpp.s

src/app/widgets/tuner.o: src/app/widgets/tuner.cpp.o

.PHONY : src/app/widgets/tuner.o

# target to build an object file
src/app/widgets/tuner.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.o
.PHONY : src/app/widgets/tuner.cpp.o

src/app/widgets/tuner.i: src/app/widgets/tuner.cpp.i

.PHONY : src/app/widgets/tuner.i

# target to preprocess a source file
src/app/widgets/tuner.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.i
.PHONY : src/app/widgets/tuner.cpp.i

src/app/widgets/tuner.s: src/app/widgets/tuner.cpp.s

.PHONY : src/app/widgets/tuner.s

# target to generate assembly for a file
src/app/widgets/tuner.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/widgets/tuner.cpp.s
.PHONY : src/app/widgets/tuner.cpp.s

src/app/window.o: src/app/window.cpp.o

.PHONY : src/app/window.o

# target to build an object file
src/app/window.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.o
.PHONY : src/app/window.cpp.o

src/app/window.i: src/app/window.cpp.i

.PHONY : src/app/window.i

# target to preprocess a source file
src/app/window.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.i
.PHONY : src/app/window.cpp.i

src/app/window.s: src/app/window.cpp.s

.PHONY : src/app/window.s

# target to generate assembly for a file
src/app/window.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/app/window.cpp.s
.PHONY : src/app/window.cpp.s

src/dash.o: src/dash.cpp.o

.PHONY : src/dash.o

# target to build an object file
src/dash.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/dash.cpp.o
.PHONY : src/dash.cpp.o

src/dash.i: src/dash.cpp.i

.PHONY : src/dash.i

# target to preprocess a source file
src/dash.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/dash.cpp.i
.PHONY : src/dash.cpp.i

src/dash.s: src/dash.cpp.s

.PHONY : src/dash.s

# target to generate assembly for a file
src/dash.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/dash.cpp.s
.PHONY : src/dash.cpp.s

src/obd/command.o: src/obd/command.cpp.o

.PHONY : src/obd/command.o

# target to build an object file
src/obd/command.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.o
.PHONY : src/obd/command.cpp.o

src/obd/command.i: src/obd/command.cpp.i

.PHONY : src/obd/command.i

# target to preprocess a source file
src/obd/command.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.i
.PHONY : src/obd/command.cpp.i

src/obd/command.s: src/obd/command.cpp.s

.PHONY : src/obd/command.s

# target to generate assembly for a file
src/obd/command.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/command.cpp.s
.PHONY : src/obd/command.cpp.s

src/obd/obd.o: src/obd/obd.cpp.o

.PHONY : src/obd/obd.o

# target to build an object file
src/obd/obd.cpp.o:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.o
.PHONY : src/obd/obd.cpp.o

src/obd/obd.i: src/obd/obd.cpp.i

.PHONY : src/obd/obd.i

# target to preprocess a source file
src/obd/obd.cpp.i:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.i
.PHONY : src/obd/obd.cpp.i

src/obd/obd.s: src/obd/obd.cpp.s

.PHONY : src/obd/obd.s

# target to generate assembly for a file
src/obd/obd.cpp.s:
	$(MAKE) -f CMakeFiles/ia.dir/build.make CMakeFiles/ia.dir/src/obd/obd.cpp.s
.PHONY : src/obd/obd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ia"
	@echo "... ia_automoc"
	@echo "... aasdk"
	@echo "... aasdk_proto"
	@echo "... autoapp"
	@echo "... btservice"
	@echo "... auto"
	@echo "... autoapp_automoc"
	@echo "... btservice_automoc"
	@echo "... auto_automoc"
	@echo "... ia_automoc.o"
	@echo "... ia_automoc.i"
	@echo "... ia_automoc.s"
	@echo "... ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.o"
	@echo "... ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.i"
	@echo "... ia_automoc.dir/qrc_resources_AQNQEL2ZF62XF6.s"
	@echo "... src/app/bluetooth.o"
	@echo "... src/app/bluetooth.i"
	@echo "... src/app/bluetooth.s"
	@echo "... src/app/config.o"
	@echo "... src/app/config.i"
	@echo "... src/app/config.s"
	@echo "... src/app/tabs/data.o"
	@echo "... src/app/tabs/data.i"
	@echo "... src/app/tabs/data.s"
	@echo "... src/app/tabs/media.o"
	@echo "... src/app/tabs/media.i"
	@echo "... src/app/tabs/media.s"
	@echo "... src/app/tabs/open_auto.o"
	@echo "... src/app/tabs/open_auto.i"
	@echo "... src/app/tabs/open_auto.s"
	@echo "... src/app/tabs/settings.o"
	@echo "... src/app/tabs/settings.i"
	@echo "... src/app/tabs/settings.s"
	@echo "... src/app/theme.o"
	@echo "... src/app/theme.i"
	@echo "... src/app/theme.s"
	@echo "... src/app/widgets/progress.o"
	@echo "... src/app/widgets/progress.i"
	@echo "... src/app/widgets/progress.s"
	@echo "... src/app/widgets/switch.o"
	@echo "... src/app/widgets/switch.i"
	@echo "... src/app/widgets/switch.s"
	@echo "... src/app/widgets/tuner.o"
	@echo "... src/app/widgets/tuner.i"
	@echo "... src/app/widgets/tuner.s"
	@echo "... src/app/window.o"
	@echo "... src/app/window.i"
	@echo "... src/app/window.s"
	@echo "... src/dash.o"
	@echo "... src/dash.i"
	@echo "... src/dash.s"
	@echo "... src/obd/command.o"
	@echo "... src/obd/command.i"
	@echo "... src/obd/command.s"
	@echo "... src/obd/obd.o"
	@echo "... src/obd/obd.i"
	@echo "... src/obd/obd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

